name: brainwavesocialapp
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializer: ^0.2.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
